id: 59e3f46dec484b95b1c2d2815e5ddf38
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_142-The_Dharani_Entering_into_Non-conceptuality-v2
  language: en
  author: ''
  volume: {}
